export const appAction = {
  TOGGLE_FILTER: 'TOGGLE_FILTER',
  TOGGLE_TAG: 'TOGGLE_TAG',
};

export const photoAction = {
  GET_PHOTO: 'GET_PHOTO',
  GET_PHOTO_RATIO: 'GET_PHOTO_RATIO',
  GET_PHOTO_RATIO_SUCCESS: 'GET_PHOTO_RATIO_SUCCESS',
  GET_PHOTO_WITH_RATIO: 'GET_PHOTO_WITH_RATIO',
  GET_PHOTO_WITH_RATIO_SUCCESS: 'GET_PHOTO_WITH_RATIO_SUCCESS',

  CHANGE_PHOTO_LIST_TYPE: 'CHANGE_PHOTO_LIST_TYPE',
};
