export const appAction = {
  TEST_ACTION: 'TEST_ACTION',
};

export const userAction = {
  TEST_ACTION: 'TEST_ACTION',
};

export const photoAction = {
  GET_PHOTO: 'GET_PHOTO',
  GET_PHOTO_RATIO: 'GET_PHOTO_RATIO',
  GET_PHOTO_RATIO_SUCCESS: 'GET_PHOTO_RATIO_SUCCESS',
  GET_PHOTO_WITH_RATIO: 'GET_PHOTO_WITH_RATIO',
  GET_PHOTO_WITH_RATIO_SUCCESS: 'GET_PHOTO_WITH_RATIO_SUCCESS',
};
